### ISSUE TITLE
File editor: 500 Internal Server Error  BINDING_ERROR - No class attribute for binding found - Please check if the binded values are public attributes of your class

### ISSUE THREAD

**Issue by christianguenter2** [oblomov-dev/a2UI5-app_tools#14]
I get this error while opening the file editor
Z2UI5_CL_TOOL_APP_01
![grafik](https://github.com/oblomov-dev/a2UI5-app_tools/assets/17437789/96658302-bce5-4021-9633-ade5c8410289)

**Comment by oblomov-dev** [comment]
Ah, yes, there was a bug with the binding. I've updated the demo, and now it should work. However, the app looks a little bit outdated with a lot of commented code, etc. Just keep it as an example for now, and I'll try to update it again next time when I find a bit more time.
